### ISSUE TITLE
Max deposit not working with Ethereum

### ISSUE THREAD

**Issue by SamDevGH** [plotx/plotx-v2-bug-tracking#2]
**Type of report**
Bug

**Page**
Deposit

**Description**
When you're depositing for the first time, and you:

1. Select Ethereum
2. Click the MAX button to deposit all your PLOT
3. Click on Deposit

The transaction fails. This is because a first-time deposit requires an approval transaction as well and when you click on the MAX button, the approval step is skipped.

What should happen is that when you click the MAX button, and this is your first time interacting with PLOT, the Approve button should appear (like it does when you enter any amount manually).

**Comment by ankitnirwal** [comment]
@Samagra-Dev , this issue is fixed now, please review once and close this issue.

**Comment by SamDevGH** [comment]
@ankitnirwal I needed to hard refresh the app to confirm the fix. Is it possible to avoid this?
